# Generated by Django 3.2.8 on 2021-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(default='img_no_img.png', max_length=500),
        ),
    ]
