# Generated by Django 3.1.7 on 2021-10-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211021_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='color',
            field=models.CharField(default='white', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetails',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
