# Generated by Django 3.2.8 on 2021-11-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211106_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='white', max_length=50),
            preserve_default=False,
        ),
    ]
